<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NavsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('navs')->delete();

        \DB::table('navs')->insert(array (
            0 =>
            array (
                'id' => 1,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 1,
                'parent_id' => 0,
                'title' => 'Nước hoa',
                'slug' => 'nuoc-hoa',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 1,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:42:36',
                'updated_at' => '2022-07-01 13:47:08',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 9,
                'parent_id' => 1,
                'title' => 'Nước hoa nam',
                'slug' => 'nuoc-hoa-nam',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:47:28',
                'updated_at' => '2022-07-01 13:47:28',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 10,
                'parent_id' => 1,
                'title' => 'Nước hoa nữ',
                'slug' => 'nuoc-hoa-nu',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 10,
                'parent_id' => 1,
                'title' => 'Nước hoa Unisex',
                'slug' => 'nuoc-hoa-unisex',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 3,
                'parent_id' => 0,
                'title' => 'Son môi',
                'slug' => 'son-moi',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 29,
                'parent_id' => 5,
                'title' => 'Son lì',
                'slug' => 'son-li',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 28,
                'parent_id' => 5,
                'title' => 'Son bóng',
                'slug' => 'son-bong',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 6,
                'parent_id' => 5,
                'title' => 'Son dưỡng',
                'slug' => 'son-duong',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 12,
                'parent_id' => 0,
                'title' => 'Skincare',
                'slug' => 'skincare',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 13,
                'parent_id' => 9,
                'title' => 'Tẩy trang',
                'slug' => 'tay-trang',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 14,
                'parent_id' => 9,
                'title' => 'Sữa rửa mặt',
                'slug' => 'sua-rua-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 15,
                'parent_id' => 9,
                'title' => 'Tẩy tế bào chết',
                'slug' => 'tay-te-bao-chet',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 17,
                'parent_id' => 9,
                'title' => 'Toner',
                'slug' => 'toner',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 16,
                'parent_id' => 9,
                'title' => 'Sữa dưỡng / Lotion',
                'slug' => 'sua-duong-lotion',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 18,
                'parent_id' => 9,
                'title' => 'Mặt nạ',
                'slug' => 'mat-na',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 19,
                'parent_id' => 9,
                'title' => 'Kem mắt / Tinh chất',
                'slug' => 'kem-mat-tinh-chat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 20,
                'parent_id' => 9,
                'title' => 'Serum / Tinh chất',
                'slug' => 'serum-tinh-chat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 21,
                'parent_id' => 9,
                'title' => 'Kem dưỡng',
                'slug' => 'kem-duong',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 22,
                'parent_id' => 9,
                'title' => 'Kem chống nắng',
                'slug' => 'kem-chong-nang',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 23,
                'parent_id' => 9,
                'title' => 'Xịt khoáng',
                'slug' => 'xit-khoang',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 24,
                'parent_id' => 9,
                'title' => 'Bộ skincare',
                'slug' => 'bo-skincare',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 62,
                'parent_id' => 9,
                'title' => 'Dụng cụ chăm sóc da',
                'slug' => 'dung-cu-cham-soc-da',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 63,
                'parent_id' => 22,
                'title' => 'Máy rửa mặt',
                'slug' => 'may-rua-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 64,
                'parent_id' => 22,
                'title' => 'Máy đắp mặt nạ',
                'slug' => 'may-dap-mat-na',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 65,
                'parent_id' => 22,
                'title' => 'Máy triệt lông',
                'slug' => 'may-triet-long',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 66,
                'parent_id' => 22,
                'title' => 'Máy massage mặt',
                'slug' => 'may-massage-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 68,
                'parent_id' => 22,
                'title' => 'Dụng cụ lăn kim',
                'slug' => 'dung-cu-lan-kim',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 69,
                'parent_id' => 22,
                'title' => 'Đá bọt',
                'slug' => 'da-bot',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 70,
                'parent_id' => 22,
                'title' => 'Trắng răng',
                'slug' => 'trang-rang',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 67,
                'parent_id' => 22,
                'title' => 'Máy xông hơi mặt',
                'slug' => 'may-xong-hoi-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 25,
                'parent_id' => 0,
                'title' => 'Makeup',
                'slug' => 'makeup',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 26,
                'parent_id' => 31,
                'title' => 'Mặt',
                'slug' => 'mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 30,
                'parent_id' => 32,
                'title' => 'Kem lót',
                'slug' => 'kem-lot',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 35,
                'parent_id' => 32,
                'title' => 'Phấn nền',
                'slug' => 'phan-nen',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 7,
                'parent_id' => 32,
                'title' => 'Kem nền',
                'slug' => 'kem-nen',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 31,
                'parent_id' => 32,
                'title' => 'Kem che khuyết điểm',
                'slug' => 'kem-che-khuyet-diem',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 33,
                'parent_id' => 32,
                'title' => 'Phấn má hồng',
                'slug' => 'phan-ma-hong',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 32,
                'parent_id' => 32,
                'title' => 'Phấn phủ',
                'slug' => 'phan-phu',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 34,
                'parent_id' => 32,
                'title' => 'Phấn bắt sáng',
                'slug' => 'phan-bat-sang',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 36,
                'parent_id' => 32,
                'title' => 'Tạo khối',
                'slug' => 'tao-khoi',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 39,
                'parent_id' => 32,
                'title' => 'Bảng màu',
                'slug' => 'bang-mau',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 37,
                'parent_id' => 32,
                'title' => 'Bộ trang điểm mặt',
                'slug' => 'bo-trang-diem-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 27,
                'parent_id' => 31,
                'title' => 'Mắt',
                'slug' => 'mat1',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 40,
                'parent_id' => 43,
                'title' => 'Chì kẻ mắt',
                'slug' => 'chi-ke-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 41,
                'parent_id' => 43,
                'title' => 'Chì kẻ mày',
                'slug' => 'chi-ke-may',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 42,
                'parent_id' => 43,
                'title' => 'Dưỡng lông mi',
                'slug' => 'duong-long-mi',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 43,
                'parent_id' => 43,
                'title' => 'Dưỡng lông mày',
                'slug' => 'duong-long-may',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 44,
                'parent_id' => 43,
                'title' => 'Kem lót mắt',
                'slug' => 'kem-lot-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 50,
                'parent_id' => 43,
                'title' => 'Mi giả',
                'slug' => 'mi-gia',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 52,
                'parent_id' => 43,
                'title' => 'Phấn mắt',
                'slug' => 'phan-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 51,
                'parent_id' => 43,
                'title' => 'Mascara',
                'slug' => 'mascara',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 38,
                'parent_id' => 43,
                'title' => 'Bảng màu mắt',
                'slug' => 'bang-mau-mat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 56,
                'parent_id' => 31,
                'title' => 'Dụng cụ makeup',
                'slug' => 'dung-cu-makeup',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 57,
                'parent_id' => 53,
                'title' => 'Bấm lông mi',
                'slug' => 'bam-long-mi',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 58,
                'parent_id' => 53,
                'title' => 'Bọt biển trang điểm',
                'slug' => 'bot-bien-trang-diem',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 59,
                'parent_id' => 53,
                'title' => 'Cọ trang điểm',
                'slug' => 'co-trang-diem',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 60,
                'parent_id' => 53,
                'title' => 'Bông tẩy trang',
                'slug' => 'bong-tay-trang',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 61,
                'parent_id' => 53,
                'title' => 'Túi đựng đồ trang điểm',
                'slug' => 'tui-dung-do-trang-diem',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 46,
                'parent_id' => 0,
                'title' => 'Quà tặng',
                'slug' => 'qua-tang',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 71,
                'parent_id' => 59,
                'title' => 'Quà tặng doanh nghiệp',
                'slug' => 'qua-tang-doanh-nghiep',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 53,
                'parent_id' => 59,
                'title' => 'Sinh Nhật',
                'slug' => 'sinh-nhat',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 48,
                'parent_id' => 59,
                'title' => 'Quà tặng nam',
                'slug' => 'qua-tang-nam',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'type' => 'PRODUCT_CATEGORY',
                'type_id' => 47,
                'parent_id' => 59,
                'title' => 'Quà tặng nữ',
                'slug' => 'qua-tang-nu',
                'link' => NULL,
                'target' => NULL,
                'icon' => NULL,
                'image_url' => NULL,
                'image_url_mobile' => NULL,
                'position' => 0,
                'status' => 1,
                'creator_id' => NULL,
                'editor_id' => NULL,
                'created_at' => '2022-07-01 13:48:45',
                'updated_at' => '2022-07-01 13:48:45',
                'deleted_at' => NULL,
            ),
        ));
    }
}
