<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 2.10(268)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateTableProducts extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();

            $table->string('name', 255);
            $table->string('slug', 255);

            $table->text('summary')->nullable();
            $table->text('content')->nullable();

            $table->integer('views')->unsigned()->default(0);

            $table->text('size_guide_table')->nullable();
            $table->text('size_guide_tutorial')->nullable();
            $table->string('size_guide_image', 255)->nullable();
            $table->text('ingredients')->nullable();

            $table->boolean('is_hot')->default(0);
            $table->boolean('is_new')->default(0);
            $table->boolean('is_limited')->default(0);
            $table->smallInteger('status')->nullable()->default(1)->index();

            $table->string('meta_title', 255)->nullable();
            $table->string('custom_slug', 255)->nullable();
            $table->text('meta_description')->nullable();

            $table->string('source', 255)->nullable();
            $table->string('source_id', 255)->nullable();

            $table->integer('creator_id')->nullable()->default(0);
            $table->integer('editor_id')->nullable()->default(0);

            $table->timestamps();
            $table->softDeletes();

            $table->index('status', 'status');
            $table->index('deleted_at', 'deleted_at');
            $table->index(['source_id', 'source'], 'source_name');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
}
