<?php

use App\Models\Product\ProductCategory;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by TablePlus 2.10(268)
 * @author https://tableplus.com
 * @source https://github.com/TablePlus/tabledump
 */
class CreateTableProductCategories extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_categories', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned()->autoIncrement();
            $table->bigInteger('parent_id')->nullable()->default(0);
            $table->string('name', 255);
            $table->string('slug', 255);
            $table->text('icon')->nullable();
            $table->text('content')->nullable();

            $table->string('type', 30)->default(ProductCategory::TYPE_PRODUCT);

            $table->integer('views')->unsigned()->default(0);
            $table->integer('position')->unsigned()->nullable();

            $table->boolean('is_hot')->default(0);
            $table->boolean('is_menu')->default(0);
            $table->boolean('is_home')->default(0);
            $table->smallInteger('status')->nullable()->default(0);

            $table->string('discount')->nullable();
            $table->date('start_day')->nullable();
            $table->date('end_day')->nullable();

            $table->string('meta_title', 255)->nullable();
            $table->string('custom_slug', 255)->nullable();
            $table->text('meta_description')->nullable();

            $table->integer('creator_id')->nullable()->default(0);
            $table->integer('editor_id')->nullable()->default(0);

            $table->timestamps();
            $table->softDeletes();

            $table->index('parent_id', 'parent_id');
            $table->index('status', 'status');
            $table->index('deleted_at', 'deleted_at');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_categories');
    }
}
